server:
  port: 9999
spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-2ze2m371107x3jcg0.mysql.rds.aliyuncs.com/read_91yuedu?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: novel
      password: rm-2ze2m371107x3jcg0
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      #配置redis缓存
      redis:
        database: 7 #数据库
        host: r-bp194f122d5c5564.redis.rds.aliyuncs.com #主机
        port: 6379 #端口号
        password: HFHe323fehf46HDBV
        timeout: 3
        pool: #连接配置
          max-active: 8 #最大连接数
          max-wait: 3 #最大等待时间
          max-idle: 3 #最大空闲连接
          min-idle: 0 #最小空闲连接
  #配置上传文件的最大限制
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

mybatis:
  type-aliases-package: com.nine.one.yuedu.read.entity
  mapper-locations: classpath:mapper/*.xml
